//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epichurco.Benj8RIDES.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\guido\\Desktop\\CerverceriaSabai\\")]
        public string PathDefecto {
            get {
                return ((string)(this["PathDefecto"]));
            }
            set {
                this["PathDefecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formatosfacturas")]
        public string DeFacturas {
            get {
                return ((string)(this["DeFacturas"]));
            }
            set {
                this["DeFacturas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formatosrides")]
        public string DeRides {
            get {
                return ((string)(this["DeRides"]));
            }
            set {
                this["DeRides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("factura-1-formato-cabecera.pdf")]
        public string EsteFormatoFacturaCabecera {
            get {
                return ((string)(this["EsteFormatoFacturaCabecera"]));
            }
            set {
                this["EsteFormatoFacturaCabecera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ride-1-formato.pdf")]
        public string EsteFormatoRide {
            get {
                return ((string)(this["EsteFormatoRide"]));
            }
            set {
                this["EsteFormatoRide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("generadasfacturas")]
        public string FacturasGeneradas {
            get {
                return ((string)(this["FacturasGeneradas"]));
            }
            set {
                this["FacturasGeneradas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("generadosrides")]
        public string RidesGenerados {
            get {
                return ((string)(this["RidesGenerados"]));
            }
            set {
                this["RidesGenerados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temporal")]
        public string CarpetaTemporal {
            get {
                return ((string)(this["CarpetaTemporal"]));
            }
            set {
                this["CarpetaTemporal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archivotemporal.pdf")]
        public string ArchivoTemporal {
            get {
                return ((string)(this["ArchivoTemporal"]));
            }
            set {
                this["ArchivoTemporal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("factura-1-formato-detalles.pdf")]
        public string EsteFormatoFacturaDetalles {
            get {
                return ((string)(this["EsteFormatoFacturaDetalles"]));
            }
            set {
                this["EsteFormatoFacturaDetalles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("factura-1-formato-totales.pdf")]
        public string EsteFormatoFacturaTotales {
            get {
                return ((string)(this["EsteFormatoFacturaTotales"]));
            }
            set {
                this["EsteFormatoFacturaTotales"] = value;
            }
        }
    }
}
